"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "pl"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    app: {
      title: "MyMidwife",
      description: "Connect with midwives for your intimate and perinatal health needs",
    },
    nav: {
      menu: "Toggle menu",
      search: "Search",
      notifications: "Notifications",
      home: "Home",
      appointments: "Appointments",
      chat: "Chat",
      diary: "Diary",
      nutrition: "Nutrition",
      bmi: "BMI Calculator",
      calendar: "Calendar",
    },
    notifications: {
      markAllRead: "Mark all as read",
      viewAll: "View all notifications",
    },
    user: {
      profile: "Profile",
      settings: "Settings",
      language: "Language",
      logout: "Logout",
    },
    language: {
      english: "English",
      polish: "Polish",
    },
    common: {
      save: "Save",
      cancel: "Cancel",
      edit: "Edit",
      delete: "Delete",
      confirm: "Confirm",
      back: "Back",
      next: "Next",
      submit: "Submit",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      close: "Close",
      open: "Open",
      view: "View",
      add: "Add",
      remove: "Remove",
      update: "Update",
      create: "Create",
      search: "Search",
      filter: "Filter",
      sort: "Sort",
      clear: "Clear",
      apply: "Apply",
      reset: "Reset",
      readMore: "Read more", // Corrected path
      review: {
        title: "Leave a Review",
        forAppointmentWith: "for appointment with",
        rating: "Your Rating",
        comment: "Your Comment",
        commentPlaceholder: "Share your experience...",
        submitReview: "Submit Review",
        toast: {
          error: "Error",
          selectRating: "Please select a rating.",
          success: "Success!",
          reviewSubmitted: "Review submitted successfully!",
          submissionFailed: "Failed to submit review. Please try again.",
        },
      },
    },
    appointments: {
      title: "Appointments",
      book: "Book Appointment",
      upcoming: "Upcoming Appointments",
      past: "Past Appointments",
      history: "Appointment History",
      noUpcoming: "No upcoming appointments",
      noPast: "No past appointments",
      reschedule: "Reschedule",
      cancel: "Cancel",
      join: "Join",
      message: "Message",
      review: "Leave Review",
      bookAgain: "Book Again",
      reviewed: "Reviewed",
      confirmed: "Confirmed",
      completed: "Completed",
      findMidwife: "Find a Midwife",
      noAppointments: "You don't have any scheduled appointments. Find a midwife and book your visit.",
      types: {
        online: "Online Consultation",
        office: "In-Office Visit",
        home: "Home Visit",
      },
    },
    search: {
      title: "Find Midwives",
      description: "Search for midwives based on location, services, and availability",
      placeholder: "Search by name, specialty, or location",
      filters: "Filters",
      location: "Location",
      specialty: "Specialty",
      availability: "Availability",
      rating: "Rating",
      experience: "Experience",
      language: "Language",
      price: "Price Range",
      results: "Search Results",
      noResults: "No midwives found",
      noResultsDescription:
        "We couldn't find any midwives matching your search criteria. Try adjusting your filters or search in a different location.",
      suggestedAlternatives: "Suggested alternatives:",
      viewProfile: "View Profile",
      bookNow: "Book Now",
      refineResults: "Refine your search results",
      city: "City",
      provinceRegion: "Province/Region",
      serviceType: "Service Type",
      serviceDeliveryFormat: "Service Delivery Format",
      minimumRating: "Minimum Rating",
      applyFilters: "Apply Filters",
      all: "All",
      lactation: "Lactation",
      birthPrep: "Birth Prep",
      gynecology: "Gynecology",
      warsaw: "Warsaw",
      lactationConsultant: "Lactation Consultant",
      inPerson: "In-person",
      certifiedLactationConsultant: "Certified Lactation Consultant",
      psychologist: "Psychologist",
      dietitian: "Dietitian",
      sexologist: "Sexologist",
      urogynecologicalTherapist: "Urogynecological Therapist",
      patronageVisits: "Patronage Visits",
      birthPreparation: "Birth Preparation",
      babywearing: "Babywearing",
      cytology: "Cytology",
      hpvVaccinations: "HPV Vaccinations",
      menopauseSupport: "Menopause Support",
      inPersonOffice: "In-person (at midwife's office)",
      inPersonHome: "In-person (at patient's home)",
      online: "Online",
      anyFormat: "Any format",
      fiveStars: "5 stars",
      fourPointFivePlus: "4.5+ stars",
      fourPlus: "4+ stars",
      anyRating: "Any rating",
    },
    bmi: {
      title: "BMI Calculator",
      description: "Enter your height and weight to calculate your Body Mass Index",
      height: "Height",
      weight: "Weight",
      calculate: "Calculate BMI",
      result: "Your BMI Result",
      category: "Category",
      units: "Units",
      metric: "Metric (cm, kg)",
      imperial: "Imperial (ft, in, lbs)",
      feet: "feet",
      inches: "inches",
      saveResult: "Save Result",
      viewTrends: "View Trends",
      nutritionPlan: "Nutrition Plan",
      recommendations: "Recommendations",
      healthRecommendations: "Health Recommendations:",
      healthConsiderations: "Health Considerations:",
      importantNote: "Important Note",
      disclaimer:
        "This BMI calculator is for informational purposes only. For personalized health advice, especially during pregnancy or if you have health conditions, please consult with your midwife or healthcare provider.",
      categories: {
        underweight: "Underweight",
        normal: "Normal weight",
        overweight: "Overweight",
        obese: "Obese",
      },
      scale: "BMI Scale",
      remaining: "remaining",
    },
    diary: {
      title: "Health Diary",
      newEntry: "New Diary Entry",
      recentEntries: "Recent Entries",
      mood: "Mood",
      symptoms: "Symptoms",
      notes: "Notes",
      date: "Date",
      bloodPressure: "Blood Pressure (mmHg)",
      systolic: "Systolic (top)",
      diastolic: "Diastolic (bottom)",
      pickDate: "Pick a date",
      selectSymptoms: "Symptoms (select all that apply)",
      additionalNotes: "Add any additional notes about how you're feeling today...",
      saveEntry: "Save Entry",
      loadMore: "Load More",
      noEntries: "No diary entries yet",
      startTracking: "Start tracking your health by creating your first diary entry.",
      moods: {
        great: "Great",
        good: "Good",
        neutral: "Neutral",
        tired: "Tired",
        bad: "Bad",
      },
      symptoms: {
        nausea: "Nausea",
        headache: "Headache",
        fatigue: "Fatigue",
        cramps: "Cramps",
        bloating: "Bloating",
        breastTenderness: "Breast Tenderness",
        insomnia: "Insomnia",
        moodSwings: "Mood Swings",
      },
    },
    chat: {
      title: "Messages",
      newMessage: "New Message",
      typeMessage: "Type a message...",
      send: "Send",
      online: "Online",
      offline: "Offline",
      noConversations: "No conversations yet",
      startConversation: "Start a conversation with a midwife by booking an appointment or viewing their profile",
      unreadMessage: "Unread message",
    },
    nutrition: {
      title: "Nutrition",
      dashboard: "Nutrition Dashboard",
      foodDiary: "Food Diary",
      mealPlanner: "Meal Planner",
      todayIntake: "Today's Intake",
      calories: "Calories",
      protein: "Protein",
      carbs: "Carbs",
      fat: "Fat",
      water: "Water",
      glasses: "glasses",
      goal: "Goal",
      progress: "Today's Nutrition Progress",
      logFood: "Log Food",
      mealPlans: "Meal Plans",
      updateBMI: "Update BMI",
      recentMeals: "Recent Meals",
      viewFullDiary: "View Full Food Diary",
      breakfast: "Breakfast",
      lunch: "Lunch",
      dinner: "Dinner",
      snacks: "Snacks",
    },
    profile: {
      title: "Profile",
      personalInfo: "Personal Information",
      preferences: "Preferences",
      healthInfo: "Health Information",
      notifications: "Notification Settings",
      privacy: "Privacy Settings",
      account: "Account Settings",
    },
    midwife: {
      profile: "Midwife Profile",
      specialty: "Specialty",
      experience: "Experience",
      education: "Education",
      certifications: "Certifications",
      languages: "Languages",
      availability: "Availability",
      pricing: "Pricing",
      reviews: "Reviews",
      about: "About",
      contact: "Contact",
      book: "Book Appointment",
      message: "Send Message",
      verifiedReviews: "verified reviews",
      selectDate: "Select a Date",
      availableSlots: "Available Time Slots",
      selectDateFirst: "Please select a date to see available slots",
      appointmentTypes: "Appointment Types",
      duration: "Duration",
      minutes: "minutes",
    },
    home: {
      hero: {
        title: "Find the perfect midwife for your needs",
        description: "Connect with qualified midwives specializing in intimate and perinatal health services",
        findMidwife: "Find a Midwife",
        aboutUs: "About Us",
      },
      stats: {
        certifiedMidwives: "Certified Midwives",
        happyPatients: "Happy Patients",
        supportAvailable: "Support Available",
        satisfactionRate: "Satisfaction Rate",
      },
      quickActions: {
        title: "Quick Actions",
        findMidwife: "Find Midwife",
        searchDescription: "Search by location & services",
        bookVisit: "Book Visit",
        scheduleDescription: "Schedule appointments",
        healthDiary: "Health Diary",
        trackDescription: "Track your wellbeing",
        bmiCalculator: "BMI Calculator",
        bmiDescription: "Check your body mass index",
        nutrition: "Nutrition",
        nutritionDescription: "Track meals & get plans",
        chat: "Chat",
        chatDescription: "Message your midwife",
      },
      upcomingAppointment: "Upcoming Appointment",
      viewAll: "View All",
      featuredMidwives: "Featured Midwives",
      healthInsights: {
        title: "Health Insights",
        bmiStatus: "BMI Status",
        normalRange: "Normal Range",
        nextCheckup: "Next Checkup",
        inTwoWeeks: "In 2 weeks",
        diaryEntries: "Diary Entries",
        fiveThisWeek: "5 this week",
      },
      progress: {
        title: "Your Progress",
        appointments: "Appointments",
        appointmentsCompleted: "12 completed",
        diaryEntries: "Diary entries",
        entriesCount: "45 entries",
        healthGoals: "Health goals",
        goalsProgress: "3 of 5 met",
      },
      healthTip: {
        title: "Today's Health Tip",
        prenatalNutrition: "Prenatal Nutrition",
        description: "Ensure you're getting enough folic acid, iron, and calcium during pregnancy for optimal health.",
        readMore: "Read More",
      },
    },
    healthTips: {
      title: "Health Tips",
      prenatalNutrition: {
        title: "Prenatal Nutrition: Eating for Two",
        description:
          "Discover essential nutrients and dietary guidelines for a healthy pregnancy. Learn what to eat and what to avoid to support both your well-being and your baby's development.",
      },
      exerciseDuringPregnancy: {
        title: "Safe Exercise During Pregnancy",
        description:
          "Understand the benefits of staying active during pregnancy and learn about safe exercises. From gentle yoga to brisk walking, find routines that suit your stage of pregnancy.",
      },
      managingMorningSickness: {
        title: "Managing Morning Sickness",
        description:
          "Tips and strategies to alleviate morning sickness. Explore dietary changes, lifestyle adjustments, and natural remedies to help you feel better during early pregnancy.",
      },
      preparingForLabor: {
        title: "Preparing for Labor and Delivery",
        description:
          "A comprehensive guide to preparing for childbirth. Learn about labor stages, pain management options, and what to pack for the hospital to ensure a smooth delivery.",
      },
      postpartumRecovery: {
        title: "Postpartum Recovery: What to Expect",
        description:
          "Navigate the postpartum period with confidence. This guide covers physical recovery, emotional changes, and self-care tips for new mothers.",
      },
    },
    about: {
      heroTitle: "About MyMidwife",
      heroSubtitle: "Connecting women with qualified midwives for comprehensive perinatal care",
      founderTitle: "Meet Asia, Our Founder",
      founderParagraph1:
        "Hey, I'm Asia, and I'm a second-year midwifery student at the Medical University of Warsaw (WUM). I created this app with the vision of revolutionizing how women access midwifery care and support throughout their pregnancy journey.",
      founderParagraph2:
        "During my studies, I noticed a significant gap between the demand for personalized midwifery care and the accessibility of qualified professionals. Many women struggle to find the right midwife who matches their specific needs, location, and preferences.",
      founderParagraph3:
        "MyMidwife was born from my passion to bridge this gap. I wanted to create a platform where women could easily connect with certified midwives, access educational resources, track their health journey, and receive the personalized care they deserve during one of the most important times in their lives.",
      founderParagraph4:
        "This app represents my commitment to improving maternal healthcare accessibility and empowering women with the tools and connections they need for a healthy, supported pregnancy experience.",
      missionValuesTitle: "Our Mission & Values",
      compassionateCareTitle: "Compassionate Care",
      compassionateCareDescription: "Providing empathetic, personalized support for every woman's unique journey",
      communityTitle: "Community",
      communityDescription: "Building connections between women and qualified healthcare professionals",
      excellenceTitle: "Excellence",
      excellenceDescription: "Ensuring the highest standards of midwifery care and professional service",
      accessibilityTitle: "Accessibility",
      accessibilityDescription: "Making quality midwifery care accessible to all women, regardless of location",
      whatOffersTitle: "What MyMidwife Offers",
      findMidwivesTitle: "Find Qualified Midwives",
      findMidwivesDescription:
        "Search and connect with certified midwives based on location, specialties, and availability",
      healthTrackingTitle: "Health Tracking",
      healthTrackingDescription:
        "Monitor your pregnancy journey with our comprehensive health diary and BMI calculator",
      appointmentManagementTitle: "Appointment Management",
      appointmentManagementDescription: "Easy scheduling and management of appointments with your chosen midwife",
      nutritionGuidanceTitle: "Nutrition Guidance",
      nutritionGuidanceDescription: "Personalized nutrition plans and meal tracking for optimal maternal health",
      directCommunicationTitle: "Direct Communication",
      directCommunicationDescription:
        "Secure messaging system to stay connected with your midwife between appointments",
      educationalResourcesTitle: "Educational Resources",
      educationalResourcesDescription: "Access to evidence-based information and tips for a healthy pregnancy",
      ctaTitle: "Ready to Start Your Journey?",
      ctaSubtitle:
        "Join thousands of women who have found their perfect midwife through MyMidwife. Start your personalized pregnancy care journey today.",
      signUpToday: "Sign Up Today",
    },
  },
  pl: {
    app: {
      title: "MyMidwife",
      description: "Połącz się z położnymi w sprawach zdrowia intymnego i okołoporodowego",
    },
    nav: {
      menu: "Przełącz menu",
      search: "Szukaj",
      notifications: "Powiadomienia",
      home: "Homepage",
      appointments: "Wizyty",
      chat: "Czat",
      diary: "Dziennik",
      nutrition: "Żywienie",
      bmi: "Kalkulator BMI",
      calendar: "Kalendarz",
    },
    notifications: {
      markAllRead: "Oznacz wszystkie jako przeczytane",
      viewAll: "Zobacz wszystkie powiadomienia",
    },
    user: {
      profile: "Profil",
      settings: "Ustawienia",
      language: "Język",
      logout: "Wyloguj",
    },
    language: {
      english: "Angielski",
      polish: "Polski",
    },
    common: {
      save: "Zapisz",
      cancel: "Anuluj",
      edit: "Edytuj",
      delete: "Usuń",
      confirm: "Potwierdź",
      back: "Wstecz",
      next: "Dalej",
      submit: "Wyślij",
      loading: "Ładowanie...",
      error: "Błąd",
      success: "Sukces",
      close: "Zamknij",
      open: "Otwórz",
      view: "Zobacz",
      add: "Dodaj",
      remove: "Usuń",
      update: "Aktualizuj",
      create: "Utwórz",
      search: "Szukaj",
      filter: "Filtruj",
      sort: "Sortuj",
      clear: "Wyczyść",
      apply: "Zastosuj",
      reset: "Resetuj",
      readMore: "Czytaj więcej", // Corrected path
      review: {
        title: "Zostaw recenzję",
        forAppointmentWith: "za wizytę z",
        rating: "Twoja ocena",
        comment: "Twój komentarz",
        commentPlaceholder: "Podziel się swoim doświadczeniem...",
        submitReview: "Wyślij recenzję",
        toast: {
          error: "Błąd",
          selectRating: "Proszę wybrać ocenę.",
          success: "Sukces!",
          reviewSubmitted: "Recenzja została pomyślnie wysłana!",
          submissionFailed: "Nie udało się wysłać recenzji. Spróbuj ponownie.",
        },
      },
    },
    appointments: {
      title: "Wizyty",
      book: "Umów wizytę",
      upcoming: "Nadchodzące wizyty",
      past: "Przeszłe wizyty",
      history: "Historia wizyt",
      noUpcoming: "Brak nadchodzących wizyt",
      noPast: "Brak przeszłych wizyt",
      reschedule: "Przełóż",
      cancel: "Anuluj",
      join: "Dołącz",
      message: "Wiadomość",
      review: "Oceń wizytę",
      bookAgain: "Umów ponownie",
      reviewed: "Oceniono",
      confirmed: "Potwierdzona",
      completed: "Zakończona",
      findMidwife: "Znajdź położną",
      noAppointments: "Nie masz zaplanowanych wizyt. Znajdź położną i umów się na wizytę.",
      types: {
        online: "Konsultacja online",
        office: "Wizyta w gabinecie",
        home: "Wizyta domowa",
      },
    },
    search: {
      title: "Znajdź położne",
      description: "Szukaj położnych według lokalizacji, usług i dostępności",
      placeholder: "Szukaj według nazwy, specjalizacji lub lokalizacji",
      filters: "Filtry",
      location: "Lokalizacja",
      specialty: "Specjalizacja",
      availability: "Dostępność",
      rating: "Ocena",
      experience: "Doświadczenie",
      language: "Język",
      price: "Zakres cenowy",
      results: "Wyniki wyszukiwania",
      noResults: "Nie znaleziono położnych",
      noResultsDescription:
        "Nie mogliśmy znaleźć położnych spełniających Twoje kryteria wyszukiwania. Spróbuj dostosować filtry lub szukać w innej lokalizacji.",
      suggestedAlternatives: "Sugerowane alternatywy:",
      viewProfile: "Zobacz profil",
      bookNow: "Umów teraz",
      refineResults: "Doprecyzuj wyniki wyszukiwania",
      city: "Miasto",
      provinceRegion: "Województwo/Region",
      serviceType: "Rodzaj usługi",
      serviceDeliveryFormat: "Format świadczenia usługi",
      minimumRating: "Minimalna ocena",
      applyFilters: "Zastosuj filtry",
      all: "Wszystkie",
      lactation: "Laktacja",
      birthPrep: "Przygotowanie do porodu",
      gynecology: "Ginekologia",
      warsaw: "Warszawa",
      lactationConsultant: "Konsultant laktacyjny",
      inPerson: "Osobiście",
      certifiedLactationConsultant: "Certyfikowany konsultant laktacyjny",
      psychologist: "Psycholog",
      dietitian: "Dietetyk",
      sexologist: "Seksuolog",
      urogynecologicalTherapist: "Terapeuta uroginekologiczny",
      patronageVisits: "Wizyty patronażowe",
      birthPreparation: "Przygotowanie do porodu",
      babywearing: "Noszenie dzieci",
      cytology: "Cytologia",
      hpvVaccinations: "Szczepienia HPV",
      menopauseSupport: "Wsparcie w menopauzie",
      inPersonOffice: "Osobiście (w gabinecie położnej)",
      inPersonHome: "Osobiście (w domu pacjentki)",
      online: "Online",
      anyFormat: "Dowolny format",
      fiveStars: "5 gwiazdek",
      fourPointFivePlus: "4,5+ gwiazdek",
      fourPlus: "4+ gwiazdek",
      anyRating: "Dowolna ocena",
    },
    bmi: {
      title: "Kalkulator BMI",
      description: "Wprowadź swój wzrost i wagę, aby obliczyć wskaźnik masy ciała",
      height: "Wzrost",
      weight: "Waga",
      calculate: "Oblicz BMI",
      result: "Twój wynik BMI",
      category: "Kategoria",
      units: "Jednostki",
      metric: "Metryczne (cm, kg)",
      imperial: "Imperialne (ft, in, lbs)",
      feet: "stopy",
      inches: "cale",
      saveResult: "Zapisz wynik",
      viewTrends: "Zobacz trendy",
      nutritionPlan: "Plan żywieniowy",
      recommendations: "Zalecenia",
      healthRecommendations: "Zalecenia zdrowotne:",
      healthConsiderations: "Uwagi zdrowotne:",
      importantNote: "Ważna uwaga",
      disclaimer:
        "Ten kalkulator BMI służy wyłącznie celom informacyjnym. W celu uzyskania spersonalizowanych porad zdrowotnych, szczególnie w czasie ciąży lub w przypadku problemów zdrowotnych, skonsultuj się z położną lub lekarzem.",
      categories: {
        underweight: "Niedowaga",
        normal: "Waga prawidłowa",
        overweight: "Nadwaga",
        obese: "Otyłość",
      },
      scale: "Skala BMI",
      remaining: "pozostało",
    },
    diary: {
      title: "Dziennik zdrowia",
      newEntry: "Nowy wpis do dziennika",
      recentEntries: "Ostatnie wpisy",
      mood: "Nastrój",
      symptoms: "Objawy",
      notes: "Notatki",
      date: "Data",
      bloodPressure: "Ciśnienie krwi (mmHg)",
      systolic: "Skurczowe (górne)",
      diastolic: "Rozkurczowe (dolne)",
      pickDate: "Wybierz datę",
      selectSymptoms: "Objawy (zaznacz wszystkie, które występują)",
      additionalNotes: "Dodaj dodatkowe notatki o tym, jak się dzisiaj czujesz...",
      saveEntry: "Zapisz wpis",
      loadMore: "Załaduj więcej",
      noEntries: "Brak wpisów w dzienniku",
      startTracking: "Zacznij śledzić swoje zdrowie, tworząc pierwszy wpis w dzienniku.",
      moods: {
        great: "Świetnie",
        good: "Dobrze",
        neutral: "Neutralnie",
        tired: "Zmęczona",
        bad: "Źle",
      },
      symptoms: {
        nausea: "Nudności",
        headache: "Ból głowy",
        fatigue: "Zmęczenie",
        cramps: "Skurcze",
        bloating: "Wzdęcia",
        breastTenderness: "Wrażliwość piersi",
        insomnia: "Bezsenność",
        moodSwings: "Wahania nastroju",
      },
    },
    chat: {
      title: "Wiadomości",
      newMessage: "Nowa wiadomość",
      typeMessage: "Napisz wiadomość...",
      send: "Wyślij",
      online: "Online",
      offline: "Offline",
      noConversations: "Brak rozmów",
      startConversation: "Rozpocznij rozmowę z położną, umówiwszy się na wizytę lub przeglądając jej profil",
      unreadMessage: "Nieprzeczytana wiadomość",
    },
    nutrition: {
      title: "Żywienie",
      dashboard: "Panel żywienia",
      foodDiary: "Dziennik żywieniowy",
      mealPlanner: "Planer posiłków",
      todayIntake: "Dzisiejsze spożycie",
      calories: "Kalorie",
      protein: "Białko",
      carbs: "Węglowodany",
      fat: "Tłuszcze",
      water: "Woda",
      glasses: "szklanki",
      goal: "Cel",
      progress: "Dzisiejszy postęp żywieniowy",
      logFood: "Zapisz jedzenie",
      mealPlans: "Plany posiłków",
      updateBMI: "Aktualizuj BMI",
      recentMeals: "Ostatnie posiłki",
      viewFullDiary: "Zobacz pełny dziennik żywieniowy",
      breakfast: "Śniadanie",
      lunch: "Obiad",
      dinner: "Kolacja",
      snacks: "Przekąski",
    },
    profile: {
      title: "Profil",
      personalInfo: "Informacje osobiste",
      preferences: "Preferencje",
      healthInfo: "Informacje zdrowotne",
      notifications: "Ustawienia powiadomień",
      privacy: "Ustawienia prywatności",
      account: "Ustawienia konta",
    },
    midwife: {
      profile: "Profil położnej",
      specialty: "Specjalizacja",
      experience: "Doświadczenie",
      education: "Wykształcenie",
      certifications: "Certyfikaty",
      languages: "Języki",
      availability: "Dostępność",
      pricing: "Cennik",
      reviews: "Opinie",
      about: "O mnie",
      contact: "Kontakt",
      book: "Umów wizytę",
      message: "Wyślij wiadomość",
      verifiedReviews: "zweryfikowanych opinii",
      selectDate: "Wybierz datę",
      availableSlots: "Dostępne terminy",
      selectDateFirst: "Wybierz datę, aby zobaczyć dostępne terminy",
      appointmentTypes: "Rodzaje wizyt",
      duration: "Czas trwania",
      minutes: "minut",
    },
    home: {
      hero: {
        title: "Znajdź idealną położną dla swoich potrzeb",
        description:
          "Połącz się z wykwalifikowanymi położnymi specjalizującymi się w zdrowiu intymnym i okołoporodowym",
        findMidwife: "Znajdź położną",
        aboutUs: "O nas",
      },
      stats: {
        certifiedMidwives: "Certyfikowane położne",
        happyPatients: "Zadowolone pacjentki",
        supportAvailable: "Wsparcie dostępne",
        satisfactionRate: "Wskaźnik zadowolenia",
      },
      quickActions: {
        title: "Szybkie akcje",
        findMidwife: "Znajdź położną",
        searchDescription: "Szukaj według lokalizacji i usług",
        bookVisit: "Umów wizytę",
        scheduleDescription: "Zaplanuj wizyty",
        healthDiary: "Dziennik zdrowia",
        trackDescription: "Śledź swoje samopoczucie",
        bmiCalculator: "Kalkulator BMI",
        bmiDescription: "Sprawdź swój wskaźnik masy ciała",
        nutrition: "Żywienie",
        nutritionDescription: "Śledź posiłki i otrzymuj plany",
        chat: "Czat",
        chatDescription: "Napisz do swojej położnej",
      },
      upcomingAppointment: "Nadchodząca wizyta",
      viewAll: "Zobacz wszystkie",
      featuredMidwives: "Polecane położne",
      healthInsights: {
        title: "Wgląd w zdrowie",
        bmiStatus: "Status BMI",
        normalRange: "Zakres normalny",
        nextCheckup: "Następna kontrola",
        inTwoWeeks: "Za 2 tygodnie",
        diaryEntries: "Wpisy w dzienniku",
        fiveThisWeek: "5 w tym tygodniu",
      },
      progress: {
        title: "Twój postęp",
        appointments: "Wizyty",
        appointmentsCompleted: "12 ukończonych",
        diaryEntries: "Wpisy w dzienniku",
        entriesCount: "45 wpisów",
        healthGoals: "Cele zdrowotne",
        goalsProgress: "3 z 5 osiągnięte",
      },
      healthTip: {
        title: "Dzisiejsza porada zdrowotna",
        prenatalNutrition: "Odżywianie w ciąży",
        description:
          "Właściwe odżywianie w ciąży jest kluczowe zarówno dla matki, jak i dziecka. Skup się na produktach bogatych w składniki odżywcze, takich jak owoce, warzywa, chude białka i pełnoziarniste produkty. Unikaj surowego mięsa, niepasteryzowanego nabiału i nadmiernej ilości kofeiny. Pij dużo wody przez cały dzień.",
      },
    },
    healthTips: {
      title: "Porady Zdrowotne",
      prenatalNutrition: {
        title: "Odżywianie w ciąży: Jedzenie dla dwojga",
        description:
          "Odkryj niezbędne składniki odżywcze i wytyczne dietetyczne dla zdrowej ciąży. Dowiedz się, co jeść, a czego unikać, aby wspierać zarówno swoje samopoczucie, jak i rozwój dziecka.",
      },
      exerciseDuringPregnancy: {
        title: "Bezpieczne ćwiczenia w ciąży",
        description:
          "Poznaj korzyści z aktywności fizycznej w ciąży i dowiedz się o bezpiecznych ćwiczeniach. Od delikatnej jogi po szybki spacer, znajdź rutyny odpowiednie dla Twojego etapu ciąży.",
      },
      managingMorningSickness: {
        title: "Radzenie sobie z porannymi mdłościami",
        description:
          "Wskazówki i strategie łagodzenia porannych mdłości. Poznaj zmiany w diecie, modyfikacje stylu życia i naturalne środki, które pomogą Ci poczuć się lepiej we wczesnej ciąży.",
      },
      preparingForLabor: {
        title: "Przygotowanie do porodu",
        description:
          "Kompleksowy przewodnik po przygotowaniach do porodu. Dowiedz się o etapach porodu, opcjach zarządzania bólem i co spakować do szpitala, aby zapewnić płynny poród.",
      },
      postpartumRecovery: {
        title: "Powrót do formy po porodzie: Czego się spodziewać",
        description:
          "Przejdź przez okres poporodowy z pewnością siebie. Ten przewodnik obejmuje powrót do zdrowia fizycznego, zmiany emocjonalne i wskazówki dotyczące samoopieki dla nowych matek.",
      },
    },
    about: {
      heroTitle: "O MyMidwife",
      heroSubtitle: "Łączymy kobiety z wykwalifikowanymi położnymi dla kompleksowej opieki okołoporodowej",
      founderTitle: "Poznaj Asię, naszą założycielkę",
      founderParagraph1:
        "Cześć, jestem Asia i jestem studentką drugiego roku położnictwa na Warszawskim Uniwersytecie Medycznym (WUM). Stworzyłam tę aplikację z wizją zrewolucjonizowania sposobu, w jaki kobiety uzyskują dostęp do opieki położniczej i wsparcia przez całą ciążę.",
      founderParagraph2:
        "Podczas studiów zauważyłam znaczącą lukę między zapotrzebowaniem na spersonalizowaną opiekę położniczą a dostępnością wykwalifikowanych specjalistów. Wiele kobiet ma trudności ze znalezieniem odpowiedniej położnej, która odpowiada ich konkretnym potrzebom, lokalizacji i preferencjom.",
      founderParagraph3:
        "MyMidwife narodziło się z mojej pasji do wypełnienia tej luki. Chciałam stworzyć platformę, na której kobiety mogłyby łatwo łączyć się z certyfikowanymi położnymi, uzyskiwać dostęp do zasobów edukacyjnych, śledzić swoją podróż zdrowotną i otrzymywać spersonalizowaną opiekę, na którą zasługują w jednym z najważniejszych okresów w ich życiu.",
      founderParagraph4:
        "Ta aplikacja reprezentuje moje zaangażowanie w poprawę dostępności opieki zdrowotnej dla matek i wzmocnienie pozycji kobiet za pomocą narzędzi i połączeń, których potrzebują do zdrowej i wspieranej ciąży.",
      missionValuesTitle: "Nasza Misja i Wartości",
      compassionateCareTitle: "Współczująca Opieka",
      compassionateCareDescription:
        "Zapewnienie empatycznego, spersonalizowanego wsparcia dla każdej kobiety w jej wyjątkowej podróży",
      communityTitle: "Społeczność",
      communityDescription: "Budowanie połączeń między kobietami a wykwalifikowanymi pracownikami służby zdrowia",
      excellenceTitle: "Doskonałość",
      excellenceDescription: "Zapewnienie najwyższych standardów opieki położniczej i profesjonalnych usług",
      accessibilityTitle: "Dostępność",
      accessibilityDescription:
        "Uczynienie wysokiej jakości opieki położniczej dostępną dla wszystkich kobiet, niezależnie od lokalizacji",
      whatOffersTitle: "Co oferuje MyMidwife",
      findMidwivesTitle: "Znajdź wykwalifikowane położne",
      findMidwivesDescription:
        "Wyszukuj i łącz się z certyfikowanymi położnymi na podstawie lokalizacji, specjalizacji i dostępności",
      healthTrackingTitle: "Śledzenie zdrowia",
      healthTrackingDescription:
        "Monitoruj swoją podróż ciążową za pomocą naszego kompleksowego dziennika zdrowia i kalkulatora BMI",
      appointmentManagementTitle: "Zarządzanie wizytami",
      appointmentManagementDescription: "Łatwe planowanie i zarządzanie wizytami u wybranej położnej",
      nutritionGuidanceTitle: "Wskazówki żywieniowe",
      nutritionGuidanceDescription:
        "Spersonalizowane plany żywieniowe i śledzenie posiłków dla optymalnego zdrowia matki",
      directCommunicationTitle: "Bezpośrednia komunikacja",
      directCommunicationDescription: "Bezpieczny system wiadomości do utrzymywania kontaktu z położną między wizytami",
      educationalResourcesTitle: "Zasoby edukacyjne",
      educationalResourcesDescription:
        "Dostęp do informacji opartych na dowodach i wskazówek dotyczących zdrowej ciąży",
      ctaTitle: "Gotowa, aby rozpocząć swoją podróż?",
      ctaSubtitle:
        "Dołącz do tysięcy kobiet, które znalazły swoją idealną położną dzięki MyMidwife. Rozpocznij swoją spersonalizowaną podróż opieki ciążowej już dziś.",
      signUpToday: "Zarejestruj się już dziś",
    },
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("pl")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "pl")) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    const keys = key.split(".")
    let value: any = translations[language]

    for (const k of keys) {
      value = value?.[k]
    }

    return value || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
